import PDFDocument from 'pdfkit';

export type SaleAgreementInput = {
  clientName: string;
  clientEmail?: string | null;
  clientPhone?: string | null;
  clientAddress?: string | null;
  beneficiaryName?: string | null;
  beneficiaryPhone?: string | null;
  beneficiaryEmail?: string | null;
  beneficiaryAddress?: string | null;
  propertyName?: string | null;
  plotReference?: string | null;
  saleReference?: string | null;
  transactionType?: string | null;
  paymentPlan?: string | null;
  estateValue: number;
  amountPaid: number;
  paymentReference?: string | null;
  issuedAt: Date;
  issuedBy: string;
};

function money(value: number) {
  return `NGN ${Number(value || 0).toLocaleString('en-NG', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function text(value: unknown, fallback = 'Not provided') {
  const v = String(value ?? '').trim();
  return v || fallback;
}

function makePdf(title: string, input: SaleAgreementInput, paragraphs: string[]) {
  return new Promise<Uint8Array>((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 54 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(new Uint8Array(Buffer.concat(chunks))));
    doc.on('error', reject);

    doc.fontSize(18).font('Helvetica-Bold').text('LANDBLAZE LIMITED', { align: 'center' });
    doc.moveDown(0.4);
    doc.fontSize(14).font('Helvetica-Bold').text(title, { align: 'center' });
    doc.moveDown();
    doc.fontSize(9).font('Helvetica').text(`Sale Reference: ${text(input.saleReference)}    Date: ${input.issuedAt.toLocaleDateString('en-NG')}`);
    doc.moveDown();

    for (const paragraph of paragraphs) {
      doc.fontSize(10.5).font('Helvetica').text(paragraph, { align: 'justify', lineGap: 4 });
      doc.moveDown(0.7);
    }

    doc.moveDown();
    doc.fontSize(9).font('Helvetica').text(`Generated by: ${text(input.issuedBy)}`);
    doc.text('This document was generated automatically from the approved sale record in Blaze Engine.');
    doc.end();
  });
}

export function buildContractOfSalePdf(input: SaleAgreementInput) {
  const property = `${text(input.propertyName)}${input.plotReference ? ` — Plot ${input.plotReference}` : ''}`;
  return makePdf('CONTRACT OF SALE', input, [
    `This Contract of Sale records the agreement between Landblaze Limited and ${text(input.clientName)} in respect of ${property}.`,
    `The agreed estate value is ${money(input.estateValue)}. The amount recorded as paid to date is ${money(input.amountPaid)}. Payment plan: ${text(input.paymentPlan)}. Payment reference: ${text(input.paymentReference)}.`,
    `Beneficiary: ${text(input.beneficiaryName, text(input.clientName))}. Beneficiary contact: ${text(input.beneficiaryPhone)} / ${text(input.beneficiaryEmail)}.`,
    `The parties acknowledge that this document is generated from the sale information approved through Landblaze's internal sales and accounts workflow. Any amendment to the sale particulars must be made through the authorised workflow and reflected in a subsequently issued document version.`,
    `Client details: ${text(input.clientName)}; email ${text(input.clientEmail)}; phone ${text(input.clientPhone)}; address ${text(input.clientAddress)}.`,
    `Property details: ${property}. Transaction type: ${text(input.transactionType)}.`,
    `Client acceptance: I/We confirm that the particulars above accurately represent the transaction recorded for this sale, subject to the terms and documentation issued by Landblaze Limited.`,
    `Client signature: ______________________________    Date: ____________________`,
    `For Landblaze Limited: _________________________    Date: ____________________`,
  ]);
}

export function buildAcknowledgementLetterPdf(input: SaleAgreementInput) {
  const property = `${text(input.propertyName)}${input.plotReference ? ` — Plot ${input.plotReference}` : ''}`;
  return makePdf('LETTER OF ACKNOWLEDGEMENT', input, [
    `Dear ${text(input.clientName)},`,
    `We acknowledge receipt of ${money(input.amountPaid)} in connection with your purchase of ${property}. Sale reference: ${text(input.saleReference)}. Payment reference: ${text(input.paymentReference)}.`,
    `The payment is recorded against an estate value of ${money(input.estateValue)} under the ${text(input.paymentPlan)} payment plan. This acknowledgement is generated from the approved transaction record and should be retained with your sales documents.`,
    `Beneficiary recorded on the sale: ${text(input.beneficiaryName, text(input.clientName))}.`,
    `Yours faithfully,`,
    `LAND BLAZE LIMITED`,
    `Authorised Sales Department`,
  ]);
}
