-- Blaze Engine v4.1
-- Transaction-specific finance document numbering metadata.
-- Safe to run repeatedly.

ALTER TABLE sales ADD COLUMN IF NOT EXISTS transaction_document_type text;

CREATE INDEX IF NOT EXISTS idx_sales_transaction_document_type
  ON sales(transaction_document_type);

-- Keep the existing generated document number in the correct dedicated field.
-- The current workflow already chooses the PDF/document from transaction nature:
-- TOP_UP -> receipt only; OUTRIGHT -> invoice + receipt; INSTALLMENT -> sales order + receipt.
CREATE OR REPLACE FUNCTION sync_sale_transaction_document_numbers()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_type text;
BEGIN
  IF NEW.invoice_number IS NULL OR NEW.invoice_number = '' THEN
    RETURN NEW;
  END IF;

  IF NEW.invoice_number LIKE 'RCT-%' THEN
    v_type := 'SALES_RECEIPT';
    NEW.sales_receipt_no := NEW.invoice_number;
    NEW.sales_invoice_no := NULL;
    NEW.sales_order_no := NULL;
  ELSIF NEW.invoice_number LIKE 'INV-%' THEN
    v_type := 'INVOICE';
    NEW.sales_invoice_no := NEW.invoice_number;
    NEW.sales_receipt_no := COALESCE(NEW.sales_receipt_no, 'RCT-' || substring(NEW.invoice_number from 5));
    NEW.sales_order_no := NULL;
  ELSIF NEW.invoice_number LIKE 'SO-%' THEN
    v_type := 'SALES_ORDER';
    NEW.sales_order_no := NEW.invoice_number;
    NEW.sales_receipt_no := COALESCE(NEW.sales_receipt_no, 'RCT-' || substring(NEW.invoice_number from 4));
    NEW.sales_invoice_no := NULL;
  ELSE
    v_type := COALESCE(NEW.transaction_document_type, 'FINANCE_DOCUMENT');
  END IF;

  NEW.transaction_document_type := v_type;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_sale_transaction_document_numbers ON sales;
CREATE TRIGGER trg_sync_sale_transaction_document_numbers
BEFORE INSERT OR UPDATE OF invoice_number, sales_receipt_no, sales_order_no, sales_invoice_no
ON sales
FOR EACH ROW
EXECUTE FUNCTION sync_sale_transaction_document_numbers();

-- Backfill existing records generated by the current workflow.
UPDATE sales
SET transaction_document_type = CASE
  WHEN invoice_number LIKE 'RCT-%' THEN 'SALES_RECEIPT'
  WHEN invoice_number LIKE 'INV-%' THEN 'INVOICE'
  WHEN invoice_number LIKE 'SO-%' THEN 'SALES_ORDER'
  ELSE transaction_document_type
END,
    sales_invoice_no = CASE
      WHEN invoice_number LIKE 'INV-%' THEN invoice_number
      ELSE sales_invoice_no
    END,
    sales_order_no = CASE
      WHEN invoice_number LIKE 'SO-%' THEN invoice_number
      ELSE sales_order_no
    END,
    sales_receipt_no = CASE
      WHEN invoice_number LIKE 'RCT-%' THEN invoice_number
      WHEN invoice_number LIKE 'INV-%' AND sales_receipt_no IS NULL THEN 'RCT-' || substring(invoice_number from 5)
      WHEN invoice_number LIKE 'SO-%' AND sales_receipt_no IS NULL THEN 'RCT-' || substring(invoice_number from 4)
      ELSE sales_receipt_no
    END
WHERE invoice_number IS NOT NULL;

-- Verification
SELECT sale_reference, transaction_type, payment_plan,
       transaction_document_type, sales_invoice_no,
       sales_order_no, sales_receipt_no, invoice_number
FROM sales
WHERE invoice_number IS NOT NULL
ORDER BY created_at DESC;
