'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
export default function Login() {
  const [identifier,setIdentifier]=useState(''); const [secret,setSecret]=useState('');
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [mode,setMode]=useState<'pin'|'password'>('pin');
  const router=useRouter();
  async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,identifier,secret})});const data=await r.json();if(!r.ok){setError(data.error||'Sign in failed');setBusy(false);return;}if(data.needsPinSetup) router.push('/profile/security'); else {router.push('/dashboard');router.refresh();}}catch{setError('Could not reach the server');setBusy(false);}}
  return <main className="login"><form className="login-card" onSubmit={submit}><div className="brand">LAND<span>BLAZE</span></div><div className="kicker">Engine</div><h1>{mode==='pin'?'Welcome back':'First-time setup'}</h1><p className="muted">{mode==='pin'?'Sign in with your username and 6-digit PIN.':'Use the email and password issued to you. After sign-in, you will create your username and PIN.'}</p>{error&&<div className="alert">{error}</div>}<div className="tabs"><button type="button" className={'btn '+(mode==='pin'?'primary':'light')} onClick={()=>{setMode('pin');setIdentifier('');setSecret('');setError('')}}>Username + PIN</button><button type="button" className={'btn '+(mode==='password'?'primary':'light')} onClick={()=>{setMode('password');setIdentifier('');setSecret('');setError('')}}>First-time setup</button></div><label>{mode==='pin'?'Username':'Email'}<input className="input" type={mode==='pin'?'text':'email'} required autoFocus value={identifier} onChange={e=>setIdentifier(e.target.value)} /></label><label>{mode==='pin'?'6-digit PIN':'Password'}<input className="input" type="password" inputMode={mode==='pin'?'numeric':undefined} maxLength={mode==='pin'?6:undefined} required value={secret} onChange={e=>setSecret(mode==='pin'?e.target.value.replace(/\D/g,''):e.target.value)} /></label><button className="btn primary full" disabled={busy}>{busy?'Signing in…':'Continue'}</button></form></main>;
}
