import {NextResponse} from 'next/server';import {requireUser} from '@/lib/guard';import {can} from '@/lib/rbac';import {sql} from '@/lib/db';
function esc(v:any){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function xls(title:string,rows:any[]){const cols=rows.length?Object.keys(rows[0]):[];const html=`<html><head><meta charset="utf-8"></head><body><h2>${esc(title)}</h2><table border="1"><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c])}</td>`).join('')}</tr>`).join('')}</table></body></html>`;return new Response(html,{headers:{'Content-Type':'application/vnd.ms-excel; charset=utf-8','Content-Disposition':`attachment; filename="${title.replace(/[^a-z0-9_-]/gi,'_')}.xls"`}})}
function pdfText(title:string,rows:any[]){const cols=rows.length?Object.keys(rows[0]):[];const lines=[title,'',cols.join(' | '),...rows.map(r=>cols.map(c=>String(r[c]??'')).join(' | '))];const escPdf=(x:string)=>x.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?').slice(0,150);const chunks:string[][]=[];for(let i=0;i<lines.length;i+=45)chunks.push(lines.slice(i,i+45));let objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids ['+chunks.map((_,i)=>`${3+i*2} 0 R`).join(' ')+'] /Count '+chunks.length+' >>'];for(let i=0;i<chunks.length;i++){const stream=`BT /F1 9 Tf 40 770 Td 12 TL ${chunks[i].map((l,j)=>(j?'T* ':'')+'('+escPdf(l)+') Tj').join(' ')} ET`;objs.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${3+chunks.length*2} 0 R >> >> /Contents ${4+i*2} 0 R >>`);objs.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`)}objs.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let pdf='%PDF-1.4\n',offs:number[]=[];objs.forEach((o,i)=>{offs[i]=pdf.length;pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const x=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(const o of offs)pdf+=String(o).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return new Response(pdf,{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${title.replace(/[^a-z0-9_-]/gi,'_')}.pdf"`}})}
export async function GET(req:Request){const s=await requireUser();const u=new URL(req.url),type=u.searchParams.get('type')||'sales',format=u.searchParams.get('format')||'xls',run=u.searchParams.get('run');let title=type,rows:any[]=[];const required:any={sales:['sale.read','sale.read_all'],expenses:['expense.read','expense.read_all','finance.workspace'],approvals:['approvals.read'],hr:['hr.workspace','payroll.read'],payroll:['payroll.read','hr.payroll'],payroll_items:['payroll.read','hr.payroll']};if(required[type]&&!required[type].some((c:string)=>can(s.role,c as any)))return NextResponse.json({error:'Forbidden'},{status:403});if(type==='payroll'){if(!['HR','CEO','ADMIN','SUPER_ADMIN','ACCOUNTANT','FINANCE_OPERATIONS'].includes(s.role))return NextResponse.json({error:'Forbidden'},{status:403});rows=await sql`select payroll_month,status,item_count,total_gross,total_allowances,total_deductions,total_net,created_at,approved_at,disbursed_at from payroll_runs order by period_start desc`}
else if(type==='payroll_items'&&run){if(!['HR','CEO','ADMIN','SUPER_ADMIN','ACCOUNTANT','FINANCE_OPERATIONS'].includes(s.role))return NextResponse.json({error:'Forbidden'},{status:403});rows=await sql`select e.employee_no,e.first_name||' '||e.last_name employee, e.department,i.base_salary,i.allowances,i.deductions,i.gross_salary,i.net_salary,i.payment_status from payroll_items i join employees e on e.id=i.employee_id where i.payroll_run_id=${run}::uuid order by employee`}
else if(type==='sales'){rows=await sql`select client_name,property_name,plot_reference,amount,status,payment_status,created_at from sales where status<>'CANCELLED' order by created_at desc limit 1000`}
else if(type==='expenses'){rows=await sql`select vendor,category,amount,status,paid_at,created_at from expenses order by created_at desc limit 1000`}
else if(type==='approvals'){rows=await sql`select entity_type,round,step,approver_role,status,comment,created_at,acted_at from approvals order by created_at desc limit 1000`}
else if(type==='hr'){rows=await sql`select employee_no,first_name,last_name,department,job_title,employment_type,employment_status,hire_date,base_salary from employees order by first_name,last_name`}
else return NextResponse.json({error:'Unknown export type'},{status:400});return format==='pdf'?pdfText(title,rows):xls(title,rows)}
